apiVersion: v2
name: microservice-chart
description: A Helm chart for deploying microservices to Kubernetes
type: application
version: 1.0.0
appVersion: "1.0"
maintainers:
  - name: DevOps Team
    email: devops@company.com
keywords:
  - microservices
  - kubernetes
  - deployment
  - aws
  - eks
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: microservice
      image: {{ .Values.global.accountId }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/{{ .Values.image.ecrRepo }}:{{ .Values.image.buildId }}