{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-chart.configmapName" . }}
  namespace: {{ include "microservice-chart.namespace" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}