{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "microservice-chart.fullname" . }}-external-secret
  namespace: {{ include "microservice-chart.namespace" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ include "microservice-chart.secretName" . }}
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "microservice-chart.labels" . | nindent 10 }}
  {{- with .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecret.data }}
  {{- if gt (len .) 0 }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}