apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "microservice-template.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-template.labels" . | nindent 4 }}
    app: {{ .Values.appName }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.appName }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- range .Values.networkPolicy.allowedIngress }}
        - namespaceSelector:
            matchLabels:
              name: {{ .namespace }}
        {{- end }}
        {{- if .Values.ingress.enabled }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.ingress.namespace }}
        {{- end }}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- if .Values.networkPolicy.rdsCidr }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.rdsCidr }}
      ports:
        {{- range .Values.networkPolicy.rdsPorts }}
        - port: {{ . }}
          protocol: TCP
        {{- end }}
    {{- end }}
    {{- if .Values.networkPolicy.redisCidr }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.redisCidr }}
      ports:
        {{- range .Values.networkPolicy.redisPorts }}
        - port: {{ . }}
          protocol: TCP
        {{- end }}
    {{- end }}
    {{- if .Values.networkPolicy.s3Endpoint }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.s3Endpoint }}
      ports:
        - port: 443
          protocol: TCP
        - port: 80
          protocol: TCP
    {{- end }}