apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "microservice-template.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-template.labels" . | nindent 4 }}
    app: {{ .Values.appName }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "microservice-template.selectorLabels" . | nindent 6 }}
      app: {{ .Values.appName }}