{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ include "microservice-chart.namespace" . }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: {{ .Values.secretStore.service }}
      region: {{ .Values.global.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "microservice-chart.serviceAccountName" . }}
{{- end }}