apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice-template.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-template.labels" . | nindent 4 }}
    app: {{ .Values.appName }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}